// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package postgres

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	GetExternalIdentityUUIDs(ctx context.Context) ([]uuid.UUID, error)
	GetIdentityUUIDs(ctx context.Context) ([]uuid.UUID, error)
	LoadActiveFlag(ctx context.Context, uid uuid.UUID) (bool, error)
	LoadActiveFlagForUpdate(ctx context.Context, uid uuid.UUID) (bool, error)
	LoadAuthForUpdate(ctx context.Context, uid uuid.UUID) (string, error)
	LoadExternalIdentity(ctx context.Context, uid uuid.UUID) (ExternalIdentity, error)
	LoadIdentity(ctx context.Context, uid uuid.UUID) (Identity, error)
	LoadSignatureForUpdate(ctx context.Context, uid uuid.UUID) ([]byte, error)
	StoreActiveFlag(ctx context.Context, arg StoreActiveFlagParams) error
	StoreAuth(ctx context.Context, arg StoreAuthParams) error
	StoreExternalIdentity(ctx context.Context, arg StoreExternalIdentityParams) error
	StoreIdentity(ctx context.Context, arg StoreIdentityParams) error
	StoreSignature(ctx context.Context, arg StoreSignatureParams) error
}

var _ Querier = (*Queries)(nil)
