// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package sqlite

import (
	"context"
)

type Querier interface {
	GetExternalIdentityUUIDs(ctx context.Context) ([]string, error)
	GetIdentityUUIDs(ctx context.Context) ([]string, error)
	LoadActiveFlag(ctx context.Context, uid string) (int64, error)
	LoadActiveFlagForUpdate(ctx context.Context, uid string) (int64, error)
	LoadAuthForUpdate(ctx context.Context, uid string) (string, error)
	LoadExternalIdentity(ctx context.Context, uid string) (ExternalIdentity, error)
	LoadIdentity(ctx context.Context, uid string) (Identity, error)
	LoadSignatureForUpdate(ctx context.Context, uid string) ([]byte, error)
	StoreActiveFlag(ctx context.Context, arg StoreActiveFlagParams) error
	StoreAuth(ctx context.Context, arg StoreAuthParams) error
	StoreExternalIdentity(ctx context.Context, arg StoreExternalIdentityParams) error
	StoreIdentity(ctx context.Context, arg StoreIdentityParams) error
	StoreSignature(ctx context.Context, arg StoreSignatureParams) error
}

var _ Querier = (*Queries)(nil)
